CREATE TABLE category(
	id SERIAL NOT NULL PRIMARY KEY,
	name varchar(60) NOT NULL UNIQUE,
	created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
