CREATE TABLE product(
	id SERIAL NOT NULL PRIMARY KEY,
	name varchar(120) NOT NULL,
	description TEXT,
	price NUMERIC(10,2) NOT NULL,
	currency varchar(5) NOT NULL DEFAULT 'USD',
	quantity INTEGER NOT NULL DEFAULT 0,
	active BOOLEAN NOT NULL DEFAULT true,
	category_id INTEGER NOT NULL REFERENCES category(id),
	created_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
